theme = "docuapi"
themesDir = "themes"
languageCode = "en-us"
baseurl = "https://docuapi.netlify.com/"
title = "Cobalt.io API Docs"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
# We include the theme by "../.." above, but we need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true
  
# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell" 

# These are commented out for now.
#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
#[[params.language_tabs]]
#key = "python"
#name = "Python"
#[[params.language_tabs]]
#key = "javascript"
#name = "Javascript"

#Languages 
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Cobalt.io API Docs"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [ 
"<a href='https://app.cobalt.io/settings/api-token' target='_new'>Create your personal API token</a>",
"<a href='https://app.swaggerhub.com/apis/CobaltLab/Cobalt_Public_API/1.3.0' target='_new'>Explore our API in Swagger</a>",
"Visit our [Help Center](https://intercom.help/cobalt/en/) and [Support Guides](https://cobaltio.zendesk.com/hc/en-us)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
